### ISSUE TITLE
leftover can be negetive in @thread-stream/index.js:134:11 

### ISSUE THREAD

**Issue by shawel** [pinojs/thread-stream#63]
logging a large content using pino ..  commenting out the exception works 

```
Worker for job  had an error {
  err: Error: overwritten
      at nextFlush (/projects/node-tasks/node_modules/thread-stream/index.js:134:11)
      at write (/projects/node-tasks/node_modules/thread-stream/index.js:366:3)
```

any idea why

**Comment by mcollina** [comment]
I don't understand the issue. What did you comment out? Could you add a script to reproduce the problem?

**Comment by shawel** [comment]
My Setup is as follows and pino.error(<largeerror>)  fails with with exception.. 
```
const transport = pino.transport({
    targets: [
      {
        target: 'pino/file',
        options: {
       
          destination: path.join(_path || LOG_PATH, `${namespace}.${today}.log`),
          sync: true,
          mkdir: true 
        }
      }]
  })

  return pino(transport)
}
```

there is a `` throw new Error('overwritten') `` on both the following functions which seems to be where the exception is coming from which i commented out.. 


```
function writeSync (stream) {
  const cb = () => {
    if (stream[kImpl].ending) {
      end(stream)
    } else if (stream[kImpl].needDrain) {
      process.nextTick(drain, stream)
    }
  }
  stream[kImpl].flushing = false

  while (stream[kImpl].buf.length !== 0) {
    const writeIndex = Atomics.load(stream[kImpl].state, WRITE_INDEX)
    let leftover = stream[kImpl].data.length - writeIndex
    if (leftover === 0) {
      flushSync(stream)
      Atomics.store(stream[kImpl].state, READ_INDEX, 0)
      Atomics.store(stream[kImpl].state, WRITE_INDEX, 0)
      continue
    } else if (leftover < 0) {
      // stream should never happen
      //throw new Error('overwritten')   <== this line executes 
    }


```

```function nextFlush (stream) {
  const writeIndex = Atomics.load(stream[kImpl].state, WRITE_INDEX)
  let leftover = stream[kImpl].data.length - writeIndex
  
  if (leftover > 0) {
    if (stream[kImpl].buf.length === 0) {
      stream[kImpl].flushing = false

      if (stream[kImpl].ending) {
        end(stream)
      } else if (stream[kImpl].needDrain) {
        process.nextTick(drain, stream)
      }

      return
    }

    let toWrite = stream[kImpl].buf.slice(0, leftover)
    let toWriteBytes = Buffer.byteLength(toWrite)
    if (toWriteBytes <= leftover) {
      stream[kImpl].buf = stream[kImpl].buf.slice(leftover)
      // process._rawDebug('writing ' + toWrite.length)
      write(stream, toWrite, nextFlush.bind(null, stream))
    } else {
      // multi-byte utf-8
      stream.flush(() => {
        Atomics.store(stream[kImpl].state, READ_INDEX, 0)
        Atomics.store(stream[kImpl].state, WRITE_INDEX, 0)

        // Find a toWrite length that fits the buffer
        // it must exists as the buffer is at least 4 bytes length
        // and the max utf-8 length for a char is 4 bytes.
        while (toWriteBytes > stream[kImpl].buf.length) {
          leftover = leftover / 2
          toWrite = stream[kImpl].buf.slice(0, leftover)
          toWriteBytes = Buffer.byteLength(toWrite)
        }
        stream[kImpl].buf = stream[kImpl].buf.slice(leftover)
        write(stream, toWrite, nextFlush.bind(null, stream))
      })
    }
  } else if (leftover === 0) {
    if (writeIndex === 0 && stream[kImpl].buf.length === 0) {
      // we had a flushSync in the meanwhile
      return
    }
    stream.flush(() => {
      Atomics.store(stream[kImpl].state, READ_INDEX, 0)
      Atomics.store(stream[kImpl].state, WRITE_INDEX, 0)
      nextFlush(stream)
    })
  } else {
    console.log("leftover: " + leftover)
    // This should never happen
   // throw new Error('overwritten')    <== this executes 
  }
```

**Comment by mcollina** [comment]
Can you include an example that will reproduce your problem? Something I can execute on my laptop.

**Comment by petru-planable** [comment]
Hello, @mcollina, thanks for the library.

The issue is related to the huge payload.

We are trying to log each request in our application using Axios interceptors, sometimes the response body is a blob of a pdf file, and in such cases, the error is thrown.

We understood that error is on our side and we filter out logged content based on response content type, but I think this issue can come in another situation when a user is trying to log an entire CSV or txt file.

I created a quick demo, may this will help you and your team to debug this issue, https://github.com/petru-planable/pino-demo. 

```
➜  pino-demo git:(master) npm -v
8.3.1
➜  pino-demo git:(master) node -v 
v17.4.0
➜  pino-demo git:(master) 
```

![image](https://user-images.githubusercontent.com/97458889/155536214-17a9750f-b7eb-4e76-a851-b7c481833564.png)

**Comment by mcollina** [comment]
@petru-planable @shawel could you please verify if https://github.com/pinojs/thread-stream/pull/65 fixes it?

**Comment by petru-planable** [comment]
@mcollina, Thanks for the quick response.
Yep, I cannot reproduce the issue using branch #65. 
Thanks.

**Comment by shawel** [comment]
ok @mcollina  thanks.  i will test shortly and get back to you..

**Comment by shawel** [comment]
This works but i think this needs to change  in Pino  package.json as well.. thanks for the fix.  sry could not respond earlier.

**Comment by mcollina** [comment]
It doesn't need an update to pino,  you should just update your dependencies.

**Comment by shawel** [comment]
Thread-stream is an internal dependency in pino declared in package.json. I used yarn resolutions to override the dependency. I am not aware of any other option.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
